export const iconPath = {
  calendar: require('../assets/icons/calendar.png'),
  close: require('../assets/icons/close.png'),
  email: require('../assets/icons/email.png'),
  facebook: require('../assets/icons/facebook.png'),
  female: require('../assets/icons/female.png'),
  genderX: require('../assets/icons/genderX.png'),
  google: require('../assets/icons/google.png'),
  location: require('../assets/icons/location.png'),
  male: require('../assets/icons/male.png'),
  nonBinary: require('../assets/icons/nonBinary.png'),
  notification: require('../assets/icons/notification.png'),
  password: require('../assets/icons/password.png'),
  person: require('../assets/icons/person.png'),
  sparkle: require('../assets/icons/sparkle.png'),
  topRightArrow: require('../assets/icons/topRightArrow.png'),
};

export const BottomIcon = {
  calendar: require('../assets/icons/BottomTab/calendar.png'),
  calendarFill: require('../assets/icons/BottomTab/calendarFill.png'),
  centerView: require('../assets/icons/BottomTab/centerView.png'),
  home: require('../assets/icons/BottomTab/home.png'),
  homeFill: require('../assets/icons/BottomTab/homeFill.png'),
  message: require('../assets/icons/BottomTab/message.png'),
  messageFill: require('../assets/icons/BottomTab/messageFill.png'),
  profile: require('../assets/icons/BottomTab/profile.png'),
  profileFill: require('../assets/icons/BottomTab/profileFill.png'),
  sideView: require('../assets/icons/BottomTab/sideView.png'),
};
