import {invalid} from 'moment';

export const imagePath = {
  appLogo: require('../assets/images/appLogo.png'),
  background: require('../assets/images/background.png'),
  bar: require('../assets/images/bar.png'),
  confirm: require('../assets/images/confirm.png'),
  dining: require('../assets/images/dining.png'),
  event: require('../assets/images/event.png'),
  experience: require('../assets/images/experience.png'),
  graphics: require('../assets/images/graphics.png'),
  homeBanner: require('../assets/images/homeBanner.png'),
  linearBackground: require('../assets/images/linearBackground.png'),
  onboarding1: require('../assets/images/onboarding1.png'),
  onboarding2: require('../assets/images/onboarding2.png'),
  onboarding3: require('../assets/images/onboarding3.png'),
  searchIcon: require('../assets/images/searchIcon.png'),
  sucessfully: require('../assets/images/sucessfully.png'),
  userSetupBackground: require('../assets/images/userSetupBackground.png'),
  userSetupBackground2: require('../assets/images/userSetupBackground2.png'),
  userSetupBackground3: require('../assets/images/userSetupBackground3.png'),
  locationImage: require('../assets/images/locationImage.png'),
  notificationImage: require('../assets/images/notificationImage.png'),
  invalidIcon: require('../assets/images/invalidIcon.png'),
  smsIcon: require('../assets/images/smsIcon.png'),
  passwordChangeIcon: require('../assets/images/passwordChangeIcon.png'),
  coffeeImage: require('../assets/images/coffeimage.png'),
  brunchImage: require('../assets/images/brunch.png'),
  dinerImage: require('../assets/images/diner.png'),
  barImage: require('../assets/images/barsImage.png'),
  experienceImage: require('../assets/images/experienceImage.png'),
  reviewImage: require('../assets/images/review.png'),
  cancelImage: require('../assets/images/cancelImage.png'),
  noNotificationImage: require('../assets/images/noNotificationImage.png'),
  noLocationImage: require('../assets/images/s_location.png'),
  filter: require('../assets/images/filter.png'),
  nothingImage: require('../assets/images/nothingImage.png'),
  burgerIcon: require('../assets/images/burgerIcon.png'),
};
