type NavigationStrings = {
  Splash: string;
  OnBoarding: string;
  Register: string;
  PhoneVerify: string;
  Confirmation: string;
  UserSetup: string;
  GenderSelection: string;
  BirthdaySelection: string;
  AboutMe: string;
  InterestSelection: string;
  BottomNavigation: string;
  MainApp: string;
  Home: string;
  MyBookings: string;
  Message: string;
  Profile: string;
  Dining: string;
  MatchingCrew: string;
  MatchingCrewBars: string;
  MatchingCrewExp: string;
  Bars: string;
  Experiences: string;
  LocationAllow: string;
  NotificationAllow: string;
  Login: string;
  ForgetPassword: string;
  VerifyScreen: string;
  NewPassword: string;
  SuccessfulPassword: string;
  DiningDetails: string;
  BarDetails: string;
  ExperienceDetails: string;
  GiveFeedback: string;
  SuccessfulFeedback: string;
  CancelBooking: string;
  CancelEvent: string;
  Notification: string;
  Location: string;
  Settings: string;
  FollowersFollowing: string;
  Followers: string;
  Following: string;
  Blocked: string;
  ChangePassword: string;
  PasswordUpdated: string;
  EditProfile: string;
  NewMessage: string;
  NewGroup: string;
  Chat: string;
  EventChat: string;
};

export const navigationStrings: NavigationStrings = {
  Splash: 'Splash',
  OnBoarding: 'OnBoarding',
  Register: 'Register',
  PhoneVerify: 'PhoneVerify',
  Confirmation: 'Confirmation',
  UserSetup: 'UserSetup',
  GenderSelection: 'GenderSelection',
  BirthdaySelection: 'BirthdaySelection',
  AboutMe: 'AboutMe',
  InterestSelection: 'InterestSelection',
  BottomNavigation: 'BottomNavigation',
  MainApp: 'BottomNavigation', // ✅ Alias pointing to the actual main route
  Home: 'Home',
  MyBookings: 'MyBookings',
  Message: 'Message',
  Profile: 'Profile',
  Dining: 'Dining',
  MatchingCrew: 'MatchingCrew',
  MatchingCrewBars: 'MatchingCrewBars',
  MatchingCrewExp: 'MatchingCrewExp',
  Bars: 'Bars',
  Experiences: 'Experiences',
  LocationAllow: 'LocationAllow',
  NotificationAllow: 'NotificationAllow',
  Login: 'Login',
  ForgetPassword: 'ForgetPassword',
  VerifyScreen: 'VerifyScreen',
  NewPassword: 'NewPassword',
  SuccessfulPassword: 'SuccessfulPassword',
  DiningDetails: 'DiningDetails',
  ExperienceDetails: 'ExperienceDetails',
  BarDetails: 'BarDetails',
  GiveFeedback: 'GiveFeedback',
  SuccessfulFeedback: 'SuccessfulFeedback',
  CancelBooking: 'CancelBooking',
  CancelEvent: 'CancelEvent',
  Notification: 'Notification',
  Location: 'Location',
  Settings: 'Settings',
  EditProfile: 'EditProfile',
  Blocked: 'Blocked',
  ChangePassword: 'ChangePassword',
  PasswordUpdated: 'PasswordUpdated',
  FollowersFollowing: 'FollowersFollowing',
  Followers: 'Followers',
  Following: 'Following',
  NewMessage: 'NewMessage',
  NewGroup: 'NewGroup',
  Chat: 'Chat',
  EventChat: 'EventChat',
};
